"""empty message

Revision ID: b3da603a1965
Revises: 
Create Date: 2025-02-08 23:56:27.863098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3da603a1965'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=15), nullable=True),
    sa.Column('Password', sa.String(length=30), nullable=True),
    sa.Column('Email', sa.String(length=50), nullable=True),
    sa.Column('SeedList', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_Username'), ['Username'], unique=True)

    op.create_table('fields',
    sa.Column('FieldId', sa.Integer(), nullable=False),
    sa.Column('OwnerId', sa.Integer(), nullable=True),
    sa.Column('FieldName', sa.String(length=30), nullable=True),
    sa.Column('NumRow', sa.Integer(), nullable=True),
    sa.Column('NumColumn', sa.Integer(), nullable=True),
    sa.Column('SeedMatrix', sa.String(), nullable=True),
    sa.Column('MineralsMatrix', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['OwnerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('FieldId')
    )
    op.create_table('seeds',
    sa.Column('SeedId', sa.Integer(), nullable=False),
    sa.Column('SeedName', sa.String(length=30), nullable=True),
    sa.Column('OwnerId', sa.Integer(), nullable=True),
    sa.Column('MinTemp', sa.Float(), nullable=True),
    sa.Column('MaxTemp', sa.Float(), nullable=True),
    sa.Column('MinWater', sa.Float(), nullable=True),
    sa.Column('MaxWater', sa.Float(), nullable=True),
    sa.Column('MinSun', sa.Float(), nullable=True),
    sa.Column('MaxSun', sa.Float(), nullable=True),
    sa.Column('GermeTime', sa.Integer(), nullable=True),
    sa.Column('WaterFreq', sa.Integer(), nullable=True),
    sa.Column('MineralGive', sa.String(length=30), nullable=True),
    sa.Column('MineralTake', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['OwnerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('SeedId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seeds')
    op.drop_table('fields')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_Username'))

    op.drop_table('user')
    # ### end Alembic commands ###
